"""1st Task Correct OTM Models 1st

Revision ID: 15167dabbe6c
Revises: f7d3101865dc
Create Date: 2026-04-14 13:27:25.654905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15167dabbe6c'
down_revision: Union[str, Sequence[str], None] = 'f7d3101865dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
