"""1st task fix oto tables 3d

Revision ID: 2976d2bf15be
Revises: 69ee857442b0
Create Date: 2026-04-11 14:23:03.616186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2976d2bf15be'
down_revision: Union[str, Sequence[str], None] = '69ee857442b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_oto_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_oto_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_id', sa.Integer(), nullable=False),
    sa.Column('parent_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['fk_id'], ['records_oto_child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_oto_parent')
    op.drop_table('records_oto_child')
    # ### end Alembic commands ###
