"""1st Task Migration

Revision ID: 331b870da1a9
Revises: 
Create Date: 2026-04-21 12:44:30.089899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331b870da1a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_mtm_child',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_mtm_parent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_otm_child',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_oto_child',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_mtm_parent_child',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['records_mtm_child.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['records_mtm_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_otm_parent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('parent_value', sa.String(), nullable=False),
    sa.Column('fk_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_id'], ['records_otm_child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_oto_parent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_id', sa.Uuid(), nullable=False),
    sa.Column('parent_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['fk_id'], ['records_oto_child.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_oto_parent')
    op.drop_table('records_otm_parent')
    op.drop_table('records_mtm_parent_child')
    op.drop_table('records_oto_child')
    op.drop_table('records_otm_child')
    op.drop_table('records_mtm_parent')
    op.drop_table('records_mtm_child')
    # ### end Alembic commands ###
