"""1st Task Fixed Name Type of Relationships

Revision ID: 47abd1214998
Revises: 15167dabbe6c
Create Date: 2026-04-15 15:02:05.645546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47abd1214998'
down_revision: Union[str, Sequence[str], None] = '15167dabbe6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_mtm_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_mtm_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_mtm_parent_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['records_mtm_child.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['records_mtm_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('records_OTO_parent_child')
    op.drop_table('records_OTO_child')
    op.drop_table('records_OTO_parent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_OTO_parent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('records_OTO_parent_pkey'))
    )
    op.create_table('records_OTO_child',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('child_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('records_OTO_child_pkey'))
    )
    op.create_table('records_OTO_parent_child',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['records_OTO_child.id'], name=op.f('records_OTO_parent_child_child_id_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['records_OTO_parent.id'], name=op.f('records_OTO_parent_child_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('records_OTO_parent_child_pkey'))
    )
    op.drop_table('records_mtm_parent_child')
    op.drop_table('records_mtm_parent')
    op.drop_table('records_mtm_child')
    # ### end Alembic commands ###
