"""1st Task OTM 1st migration after name fix

Revision ID: 7336d15862a9
Revises: b02b82b15186
Create Date: 2026-04-15 19:27:22.123255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7336d15862a9'
down_revision: Union[str, Sequence[str], None] = 'b02b82b15186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_otm_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_otm_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_value', sa.String(), nullable=False),
    sa.Column('fk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_id'], ['records_otm_child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_otm_parent')
    op.drop_table('records_otm_child')
    # ### end Alembic commands ###
