"""1st task mtm 4th migration

Revision ID: 919f247b8dbf
Revises: 96b52972d6f2
Create Date: 2026-04-12 19:34:22.696162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919f247b8dbf'
down_revision: Union[str, Sequence[str], None] = '96b52972d6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_mtm_parent_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['records_mtm_child.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['records_mtm_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_mtm_parent_child')
    # ### end Alembic commands ###
