"""1st Task Fixed Name Type of Relationships 2d migration

Revision ID: b228a4f0181b
Revises: 47abd1214998
Create Date: 2026-04-15 15:09:02.947152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b228a4f0181b'
down_revision: Union[str, Sequence[str], None] = '47abd1214998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_OTO_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_OTO_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_id', sa.Integer(), nullable=False),
    sa.Column('parent_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['fk_id'], ['records_OTO_child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('records_oto_parent')
    op.drop_table('records_oto_child')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_oto_child',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('child_value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('records_oto_child_pkey'))
    )
    op.create_table('records_oto_parent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_id'], ['records_oto_child.id'], name=op.f('records_oto_parent_fk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('records_oto_parent_pkey'))
    )
    op.drop_table('records_OTO_parent')
    op.drop_table('records_OTO_child')
    # ### end Alembic commands ###
