"""1st task otm 1st migration

Revision ID: d24de23eccb2
Revises: 2976d2bf15be
Create Date: 2026-04-12 17:44:07.758813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24de23eccb2'
down_revision: Union[str, Sequence[str], None] = '2976d2bf15be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_otm_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_otm_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_otm_parent')
    op.drop_table('records_otm_child')
    # ### end Alembic commands ###
